server: 
  port : 8083

reminder: 
  phraseEndpoint : http://learner-service/reminder/v1/expression?id=
  countEndpoint : http://learner-service/reminder/v1/length
  saveEndpont : http://admin-service/AdminReminder/v1/save
  minInteger : 1

spring: 
  application:
    name: logic-service
  config:
    import: optional:configserver:http://localhost:8889